[build]
  functions = "netlify/functions"

[dev]
  port = 8889
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/shipping"
  to = "/.netlify/functions/shipping"
  status = 200

[[redirects]]
  from = "/orders"
  to = "/.netlify/functions/orders"
  status = 200

[[redirects]]
  from = "/send-email"
  to = "/.netlify/functions/send-email"
  status = 200