version: '3.8'

# Project name for isolation
name: toaste

services:
  # Cloudflare Tunnel for Toasté
  cloudflared:
    container_name: toaste-cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TOASTE_CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - toaste-network
    depends_on:
      - api
      - pocketbase
    labels:
      - "com.toaste.project=toaste"
      - "com.toaste.service=cloudflared"
    logging:
      driver: json-file
      options:
        max-size: 2m
        max-file: "10"

  # PocketBase Database
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: toaste-pocketbase
    restart: unless-stopped
    ports:
      - "8091:8090"  # Changed from 8090 to avoid conflict with qBittorrent
    volumes:
      - pocketbase_data:/pb_data
      - ./pocketbase/pb_migrations:/pb_migrations
    environment:
      - PB_ENCRYPTION_KEY=${PB_ENCRYPTION_KEY}
    networks:
      - toaste-network
    labels:
      - "com.toaste.project=toaste"
      - "com.toaste.service=pocketbase"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Node.js REST API
  api:
    build: .
    container_name: toaste-api
    restart: unless-stopped
    ports:
      - "3001:3000"  # Changed from 3000 to avoid potential conflicts
    environment:
      - NODE_ENV=production
      - PORT=3000
      - POCKETBASE_URL=http://pocketbase:8090
      - POCKETBASE_ADMIN_EMAIL=${POCKETBASE_ADMIN_EMAIL}
      - POCKETBASE_ADMIN_PASSWORD=${POCKETBASE_ADMIN_PASSWORD}
      - CORS_ORIGIN=https://toastebikepolo.ca
    depends_on:
      pocketbase:
        condition: service_healthy
    networks:
      - toaste-network
    labels:
      - "com.toaste.project=toaste"
      - "com.toaste.service=api"
    volumes:
      - ./logs:/app/logs

volumes:
  pocketbase_data:
    name: toaste_pocketbase_data
    labels:
      - "com.toaste.project=toaste"

networks:
  toaste-network:
    name: toaste-network
    driver: bridge
    labels:
      - "com.toaste.project=toaste"
